version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_tanstack
        ports:
            - '27017:27017'
        volumes:
            - tanstack:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

volumes:
    tanstack:
